"""Deterministic SOPHY whole-body geometry kernel.

This module defines identity geometry, not anthropometric approximation and not
project packaging.  Canonical coordinates are normalized to the master scale
``H`` and instantiated in millimetres.  Only right-side laws are authored;
left-side laws are generated by reflection through the midsagittal plane.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
import json
import math
from typing import Any, Dict, Iterable, Mapping, Optional, Tuple


SOPHY_GEOMETRY_CANON_VERSION = "1.0.0"
PHI = (1.0 + math.sqrt(5.0)) / 2.0

_PROVENANCE_CANON = "PHY/SOPHY canonical design law"
_PROVENANCE_DERIVED = "derived from PHY/SOPHY canonical design law"
_VITRUVIUS_SOURCE = (
    "https://www.gutenberg.org/files/20239/20239-h/20239-h.htm#Page_72"
)


class CanonIntegrityError(ValueError):
    """Raised when imported geometry is not an exact canon instantiation."""


@dataclass(frozen=True, slots=True)
class Point3:
    """Immutable right-handed XYZ point or vector."""

    x: float
    y: float
    z: float

    def scaled(self, factor: float) -> "Point3":
        return Point3(self.x * factor, self.y * factor, self.z * factor)

    def mirror_x(self) -> "Point3":
        return Point3(-self.x, self.y, self.z)

    def plus(self, other: "Point3") -> "Point3":
        return Point3(self.x + other.x, self.y + other.y, self.z + other.z)

    def as_list(self) -> list[float]:
        return [self.x, self.y, self.z]

    @classmethod
    def from_iterable(cls, values: Iterable[float]) -> "Point3":
        x, y, z = values
        return cls(float(x), float(y), float(z))


@dataclass(frozen=True, slots=True)
class CanonicalLandmark:
    """One immutable node in the normalized canonical landmark graph."""

    canonical_id: str
    family: str
    parent_frame: str
    side: str
    normalized: Point3
    coordinates_mm: Point3
    derivation_operator: str
    derivation_inputs: Tuple[str, ...]
    provenance: str
    tolerance_category: str = "canonical_exact"
    mirrored_from: Optional[str] = None
    downstream_dependents: Tuple[str, ...] = ()

    def to_dict(self) -> Dict[str, Any]:
        derivation: Dict[str, Any] = {
            "operator": self.derivation_operator,
            "inputs": list(self.derivation_inputs),
        }
        if self.mirrored_from is not None:
            derivation["mirrored_from"] = self.mirrored_from
        return {
            "canonical_id": self.canonical_id,
            "family": self.family,
            "parent_frame": self.parent_frame,
            "side": self.side,
            "normalized_coordinates_H": self.normalized.as_list(),
            "coordinates_mm": self.coordinates_mm.as_list(),
            "derivation": derivation,
            "provenance": self.provenance,
            "tolerance_category": self.tolerance_category,
            "downstream_dependents": list(self.downstream_dependents),
        }


@dataclass(frozen=True, slots=True)
class _LandmarkLaw:
    canonical_id: str
    family: str
    parent_frame: str
    side: str
    normalized: Point3
    downstream_dependents: Tuple[str, ...] = ()
    mirror_id: Optional[str] = None

    def manifest(self) -> Dict[str, Any]:
        result = {
            "canonical_id": self.canonical_id,
            "family": self.family,
            "parent_frame": self.parent_frame,
            "side": self.side,
            "normalized_coordinates_H": self.normalized.as_list(),
            "operator": "scale_normalized_by_H",
            "downstream_dependents": list(self.downstream_dependents),
        }
        if self.mirror_id is not None:
            result["mirror_id"] = self.mirror_id
        return result


_MIDLINE_LAWS: Tuple[_LandmarkLaw, ...] = (
    _LandmarkLaw(
        canonical_id="body.plantar_midpoint",
        family="lower_limb",
        parent_frame="SOPHY_CANON",
        side="MIDLINE",
        normalized=Point3(0.0, 0.0, 0.0),
        downstream_dependents=("construction.canonical_circle", "construction.vitruvian_square"),
    ),
    _LandmarkLaw(
        canonical_id="body.canonical_center",
        family="body_center",
        parent_frame="SOPHY_CANON",
        side="MIDLINE",
        normalized=Point3(0.0, 0.0, 0.5),
        downstream_dependents=("construction.canonical_circle",),
    ),
    _LandmarkLaw(
        canonical_id="cranial.vertex",
        family="cranial",
        parent_frame="SOPHY_CANON",
        side="MIDLINE",
        normalized=Point3(0.0, 0.0, 1.0),
        downstream_dependents=("construction.canonical_circle", "construction.vitruvian_square"),
    ),
)

_RIGHT_SIDE_LAWS: Tuple[_LandmarkLaw, ...] = (
    _LandmarkLaw(
        canonical_id="construction.arm_span_endpoint.right",
        family="upper_limb",
        parent_frame="SOPHY_CANON",
        side="RIGHT",
        normalized=Point3(0.5, 0.0, 0.5),
        downstream_dependents=("dimensions.arm_span", "construction.canonical_circle"),
        mirror_id="construction.arm_span_endpoint.left",
    ),
)

_DEFERRED_IDENTITY_DECISIONS: Tuple[Dict[str, str], ...] = (
    {
        "decision_id": "anatomical_navel_coordinate",
        "status": "unbound",
        "reason": "Vitruvius describes a navel-centred spread-pose circle, but BODY has not selected SOPHY's normalized navel coordinate.",
    },
    {
        "decision_id": "anatomical_phi_bindings",
        "status": "unbound",
        "reason": "The phi operators are executable, but no anatomical landmark may inherit them from symbolic language alone.",
    },
    {
        "decision_id": "head_face_hand_foot_and_limb_ratios",
        "status": "unbound",
        "reason": "Historical fractions and legacy anthropometric values remain comparison data until adopted as explicit SOPHY design law.",
    },
    {
        "decision_id": "neutral_pose_joint_landmarks",
        "status": "unbound",
        "reason": "The neutral pose and global frame are fixed; joint-centre coordinates require a canon revision after ratio selection.",
    },
    {
        "decision_id": "canonical_neutral_face",
        "status": "unbound",
        "reason": "The facial schema is specified in documentation; identity coordinates require a dedicated canon decision and revision.",
    },
)


def golden_major(total: float) -> float:
    """Return the major segment of ``total`` under golden division."""

    return float(total) / PHI


def golden_minor(total: float) -> float:
    """Return the minor segment of ``total`` under golden division."""

    return float(total) / (PHI * PHI)


def golden_recurse(total: float, depth: int, branch: str = "major") -> float:
    """Apply one named golden-section branch repeatedly.

    This is a proportional operator, not an anatomical binding.  Binding its
    output to an identity landmark changes the canon and therefore requires an
    explicit canon revision.
    """

    if depth < 0:
        raise ValueError("depth must be non-negative")
    if branch not in {"major", "minor"}:
        raise ValueError("branch must be 'major' or 'minor'")
    value = float(total)
    operator = golden_major if branch == "major" else golden_minor
    for _ in range(depth):
        value = operator(value)
    return value


def _law_manifest() -> Dict[str, Any]:
    return {
        "canon_version": SOPHY_GEOMETRY_CANON_VERSION,
        "master_variables": ["H"],
        "coordinate_system": {
            "handedness": "right_handed",
            "origin": "body.plantar_midpoint",
            "axes": {
                "x": "subject_right",
                "y": "subject_anterior",
                "z": "superior",
            },
            "midsagittal_plane": "x = 0",
            "units": "mm",
        },
        "neutral_reference_pose": {
            "id": "SOPHY_NEUTRAL_T_POSE_V1",
            "status": "global_frame_and_span_construction_bound; joint landmarks deferred",
        },
        "canonical_dimensions": {
            "standing_height": "H",
            "arm_span": "H",
        },
        "symmetry": {
            "law": "LEFT(P) = mirror_x(RIGHT(P))",
            "plane": "x = 0",
            "independently_authored_left_landmarks": False,
        },
        "constructions": {
            "vitruvian_square": {
                "plane": "XZ",
                "x_min": "-H/2",
                "x_max": "H/2",
                "z_min": "0",
                "z_max": "H",
                "classification": _PROVENANCE_CANON,
            },
            "canonical_circle": {
                "plane": "XZ",
                "center": "body.canonical_center",
                "radius": "H/2",
                "classification": _PROVENANCE_CANON,
                "historical_attribution": "none; this is an inscribed SOPHY construction, not a reconstruction of Leonardo's circle",
            },
        },
        "phi": {
            "constant": "(1 + sqrt(5)) / 2",
            "operators": ["golden_major", "golden_minor", "golden_recurse"],
            "active_anatomical_bindings": [],
        },
        "landmark_laws": [law.manifest() for law in _MIDLINE_LAWS + _RIGHT_SIDE_LAWS],
    }


def _law_hash() -> str:
    encoded = json.dumps(_law_manifest(), sort_keys=True, separators=(",", ":")).encode("utf-8")
    return sha256(encoded).hexdigest()


@dataclass(frozen=True, slots=True)
class CanonicalGeometry:
    """Immutable instance of one supported SOPHY canon revision at scale ``H``."""

    height_mm: float
    canon_version: str
    canon_law_hash: str
    landmarks: Tuple[CanonicalLandmark, ...]

    @property
    def standing_height_mm(self) -> float:
        return self.height_mm

    @property
    def arm_span_mm(self) -> float:
        return self.height_mm

    @property
    def circle_radius_mm(self) -> float:
        return self.height_mm / 2.0

    def landmark(self, canonical_id: str) -> CanonicalLandmark:
        for landmark in self.landmarks:
            if landmark.canonical_id == canonical_id:
                return landmark
        raise KeyError(canonical_id)

    def to_dict(self) -> Dict[str, Any]:
        half = self.height_mm / 2.0
        return {
            "schema_path": "skeleton/schema/sophy_canonical_geometry.schema.json",
            "artifact": "SOPHY_CANONICAL_GEOMETRY",
            "canon": {
                "version": self.canon_version,
                "law_hash_sha256": self.canon_law_hash,
                "authority": "BODY.md",
            },
            "instance": {
                "master_variable": "H",
                "height_mm": self.height_mm,
                "units": "mm",
            },
            "coordinate_system": _law_manifest()["coordinate_system"],
            "neutral_reference_pose": _law_manifest()["neutral_reference_pose"],
            "midsagittal_plane": {"equation": "x = 0", "normal": [1.0, 0.0, 0.0]},
            "constants": {
                "phi": PHI,
                "phi_expression": "(1 + sqrt(5)) / 2",
            },
            "canonical_dimensions_mm": {
                "standing_height": self.standing_height_mm,
                "arm_span": self.arm_span_mm,
            },
            "canonical_dimension_derivations": {
                "standing_height": {"operator": "identity", "inputs": ["H"]},
                "arm_span": {"operator": "identity", "inputs": ["H"]},
            },
            "symmetry": _law_manifest()["symmetry"],
            "constructions": {
                "vitruvian_square": {
                    "classification": _PROVENANCE_CANON,
                    "historical_basis": "Vitruvius Book III, Chapter I: height equals outstretched arm span.",
                    "historical_source": _VITRUVIUS_SOURCE,
                    "plane": "XZ",
                    "minimum_mm": [-half, 0.0, 0.0],
                    "maximum_mm": [half, 0.0, self.height_mm],
                    "center_landmark": "body.canonical_center",
                },
                "canonical_circle": {
                    "classification": _PROVENANCE_CANON,
                    "historical_attribution": "none",
                    "historical_boundary": "Not the Vitruvian/Leonardian navel-centred spread-pose circle.",
                    "plane": "XZ",
                    "center_landmark": "body.canonical_center",
                    "radius_mm": self.circle_radius_mm,
                    "cardinal_landmarks": [
                        "body.plantar_midpoint",
                        "cranial.vertex",
                        "construction.arm_span_endpoint.left",
                        "construction.arm_span_endpoint.right",
                    ],
                },
            },
            "proportional_operators": {
                "golden_major": {"expression": "segment / phi", "identity_binding": None},
                "golden_minor": {"expression": "segment / phi^2", "identity_binding": None},
                "golden_recurse": {
                    "expression": "repeat(golden_major|golden_minor, depth)",
                    "identity_binding": None,
                },
            },
            "landmarks": [landmark.to_dict() for landmark in self.landmarks],
            "deferred_identity_decisions": [dict(row) for row in _DEFERRED_IDENTITY_DECISIONS],
            "provenance": {
                "historical_reference": {
                    "source": _VITRUVIUS_SOURCE,
                    "use": "provenance and comparison; only explicitly adopted rules are executable canon",
                },
                "symbolic_inheritance": {
                    "source": "SOUL.md",
                    "use": "non-operational until formalized in BODY and this kernel",
                },
            },
        }

    def to_json(self, *, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, sort_keys=True) + "\n"

    @classmethod
    def from_dict(cls, payload: Mapping[str, Any]) -> "CanonicalGeometry":
        try:
            version = str(payload["canon"]["version"])
            height_mm = float(payload["instance"]["height_mm"])
        except (KeyError, TypeError, ValueError) as exc:
            raise CanonIntegrityError("canonical payload is missing version or height") from exc
        geometry = instantiate_sophy_canon(height_mm, canon_version=version)
        if dict(payload) != geometry.to_dict():
            raise CanonIntegrityError(
                "payload does not exactly match the deterministic canon instantiation"
            )
        return geometry


def _instantiate_landmark(law: _LandmarkLaw, height_mm: float) -> CanonicalLandmark:
    return CanonicalLandmark(
        canonical_id=law.canonical_id,
        family=law.family,
        parent_frame=law.parent_frame,
        side=law.side,
        normalized=law.normalized,
        coordinates_mm=law.normalized.scaled(height_mm),
        derivation_operator="scale_normalized_by_H",
        derivation_inputs=("H",),
        provenance=_PROVENANCE_CANON,
        downstream_dependents=law.downstream_dependents,
    )


def _mirror_landmark(right: CanonicalLandmark, left_id: str) -> CanonicalLandmark:
    return CanonicalLandmark(
        canonical_id=left_id,
        family=right.family,
        parent_frame=right.parent_frame,
        side="LEFT",
        normalized=right.normalized.mirror_x(),
        coordinates_mm=right.coordinates_mm.mirror_x(),
        derivation_operator="mirror_x",
        derivation_inputs=(right.canonical_id, "midsagittal_plane"),
        provenance=_PROVENANCE_DERIVED,
        mirrored_from=right.canonical_id,
        downstream_dependents=right.downstream_dependents,
    )


def instantiate_sophy_canon(
    height_mm: float,
    *,
    canon_version: str = SOPHY_GEOMETRY_CANON_VERSION,
) -> CanonicalGeometry:
    """Return ``SOPHY_CANON(H, version)`` as deterministic coordinates.

    Only the current revision is supported.  Loading a historical revision must
    use code that implements that revision rather than silently applying current
    equations to an old version label.
    """

    height = float(height_mm)
    if not math.isfinite(height) or height <= 0.0:
        raise ValueError("H must be a finite positive height in millimetres")
    if canon_version != SOPHY_GEOMETRY_CANON_VERSION:
        raise ValueError(
            f"unsupported canon version {canon_version!r}; "
            f"supported={SOPHY_GEOMETRY_CANON_VERSION!r}"
        )

    landmarks = [_instantiate_landmark(law, height) for law in _MIDLINE_LAWS]
    for law in _RIGHT_SIDE_LAWS:
        right = _instantiate_landmark(law, height)
        landmarks.append(right)
        if law.mirror_id is None:
            raise RuntimeError(f"right-side law {law.canonical_id} has no mirror target")
        landmarks.append(_mirror_landmark(right, law.mirror_id))

    return CanonicalGeometry(
        height_mm=height,
        canon_version=canon_version,
        canon_law_hash=_law_hash(),
        landmarks=tuple(sorted(landmarks, key=lambda item: item.canonical_id)),
    )
