FROM nvidia/cuda:12.2.0-base-ubuntu22.04
WORKDIR /app
COPY . /app
RUN apt-get update && apt-get install -y python3-pip && \
    pip3 install ray[gpu]==2.9.3 stable-baselines3 gymnasium
CMD ["python3", "bin/run_curriculum.py"]
