name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pandas pybullet==3.2.5 ikpy scipy matplotlib
        pip install gymnasium stable-baselines3
    - name: Run tests
      run: pytest -q
    - name: Smoke curriculum
      run: PYTHONPATH=. python bin/run_curriculum.py
    - name: Validate skeleton (organic)
      run: python -m eval_skeleton --material organic --export-dir reports/organic
    - name: Validate skeleton (Ti6Al4V)
      run: python -m eval_skeleton --material Ti6Al4V --export-dir reports/ti
    - name: Run demos
      run: |
        PYTHONPATH=. python bin/demo_healing.py --output healing.png
        PYTHONPATH=. python bin/demo_reflexes.py --output reflex.txt
    - name: Upload demo artifacts
      uses: actions/upload-artifact@v4
      with:
        name: demos
        path: |
          healing.png
          reflex.txt
    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: validation-reports
        path: reports/
