name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pandas pybullet==3.2.5 ikpy scipy matplotlib
        pip install gymnasium stable-baselines3 fastapi uvicorn httpx
        pip install reportlab
    - name: Run tests
      run: pytest -q
    - name: Hardware benches
      run: |
        PYTHONPATH=. python bin/rt_monitor.py || true
        PYTHONPATH=. python bin/generate_tcf.py
    - name: Build Yocto image
      run: deploy/yocto_builder.sh yocto_artifact
    - name: QEMU RT kernel smoke
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-x86
        qemu-system-x86_64 --version
    - name: Run benchmark smoke
      run: PYTHONPATH=. python bin/run_benchmark.py
    - name: Build Docker image
      run: |
        docker --version || echo "no docker"
    - name: Smoke curriculum
      run: PYTHONPATH=. python bin/run_curriculum.py
    - name: Validate skeleton (organic)
      run: python -m eval_skeleton --material organic --export-dir reports/organic
    - name: Validate skeleton (Ti6Al4V)
      run: python -m eval_skeleton --material Ti6Al4V --export-dir reports/ti
    - name: Run demos
      run: |
        PYTHONPATH=. python bin/demo_healing.py --output healing.png
        PYTHONPATH=. python bin/demo_reflexes.py --output reflex.txt
        PYTHONPATH=. python bin/demo_language_pick.py > lang.txt
        PYTHONPATH=. python bin/demo_pass_the_cube.py > pass.txt
        PYTHONPATH=. python bin/demo_stop_button.py > stop.txt
    - name: Upload demo artifacts
      uses: actions/upload-artifact@v4
      with:
        name: demos
        path: |
          healing.png
          reflex.txt
          lang.txt
          pass.txt
          stop.txt
    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: validation-reports
        path: reports/
